version: "3.8"
services:
  db:
    container_name: palapi-mysql
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TCP_PORT=${MYSQL_PORT}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
    networks:
      - dockerinternal
    volumes:
      - ./mysqldb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=$MYSQL_PASSWORD mysqladmin -u ${MYSQL_USER} ping -P ${MYSQL_PORT} | grep 'mysqld is alive' || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 1m

  api:
    depends_on:
      - db
    container_name: palapi-fast_api
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SQL_PORT=${MYSQL_PORT}
      - SQL_HOST=${SQL_HOST}
      - DOCS_URL=${DOCS_URL}
      - REDOC_URL=${REDOC_URL}
      - HTTP_PORT=${HTTP_PORT}
    build:
      context: .
      args:
        - HTTP_PORT=${HTTP_PORT}
    restart: unless-stopped
    networks:
      - dockerinternal
    #ports:
    #  - ${HTTP_PORT}:${HTTP_PORT}
    healthcheck:
      test: ["CMD-SHELL", "curl -i http://localhost:${HTTP_PORT}/health 2>/dev/null || exit 1"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 1m

networks:
  dockerinternal:
    name: dockerinternal

volumes:
  db-data:
