services:
  db:
    container_name: palapi-mysql
    image: mysql:8.0.36
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
    networks:
      - dockerinternal
    volumes:
      - ./mysqldb:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
  api:
    depends_on:
      - db
    container_name: palapi-fast_api
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - SQL_HOST=${SQL_HOST}
    build: .
    restart: unless-stopped
    networks:
      - dockerinternal
#    ports:
#      - 8000:8000

networks:
  dockerinternal:
    name: dockerinternal

volumes:
  db-data:
